baseURL: https://www.colim.us
languageCode: en-us
title: Central Ohio Lutheran Immigrant Mission

menu:
  main:
  - name: Home
    url: '/'
    weight: 1

  - name: Newsletters
    url: '/newsletters/'
    weight: 2

  - name: F.A.Q.
    url: '/faq/'
    weight: 3

  - name: Gallery
    url: '/gallery/'
    weight: 4

  social:
  - name: youtube
    url: https://www.youtube.com/channel/UCP5ugWoXbwz1ccd-AisWz4Q